import { Verse } from '@/types';

export const VERSES: Verse[] = [
  // Anxiety
  {
    id: 'phil_4_6-7',
    reference: 'Philippians 4:6-7',
    text: 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.',
    tags: ['anxiety', 'peace', 'prayer'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/phil_4_6-7.mp3?alt=media&token=e60ecdd6-996e-4f3e-b0b6-520cf97c346d',
    duration: 25,
  },
  {
    id: 'matt_6_34',
    reference: 'Matthew 6:34',
    text: 'Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.',
    tags: ['anxiety', 'worry', 'trust'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/matt_6_34.mp3?alt=media&token=30b9f841-5c0c-407f-8b28-30ce4e47ed57',
    duration: 12,
  },
  {
    id: '1_pet_5_7',
    reference: '1 Peter 5:7',
    text: 'Cast all your anxiety on him because he cares for you.',
    tags: ['anxiety', 'care', 'trust'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/1pet_5_7.mp3?alt=media&token=3681c8b2-f5e1-4e8d-8859-582df04850f7',
    duration: 8,
  },
  
  // Fear
  {
    id: 'isa_41_10',
    reference: 'Isaiah 41:10',
    text: 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.',
    tags: ['fear', 'strength', 'courage'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/isa_41_10.mp3?alt=media&token=5484c187-45ef-4f87-82d8-eac932b987d0',
    duration: 18,
  },
  {
    id: 'ps_23_4',
    reference: 'Psalm 23:4',
    text: 'Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.',
    tags: ['fear', 'comfort', 'protection'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_23_4.mp3?alt=media&token=58944986-2b44-4886-8b8b-fcb248526aad',
    duration: 14,
  },
  {
    id: '2_tim_1_7',
    reference: '2 Timothy 1:7',
    text: 'For God has not given us a spirit of fear, but of power and of love and of a sound mind.',
    tags: ['fear', 'power', 'courage'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/2tim_1_7.mp3?alt=media&token=cafc4aa2-6c08-43e5-be2c-2f3973d6881f',
    duration: 11,
  },
  
  // Grief
  {
    id: 'ps_34_18',
    reference: 'Psalm 34:18',
    text: 'The Lord is close to the brokenhearted and saves those who are crushed in spirit.',
    tags: ['grief', 'comfort', 'healing'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_34_18.mp3?alt=media&token=19268a82-4db8-4f95-9488-784832614b42',
    duration: 10,
  },
  {
    id: 'matt_5_4',
    reference: 'Matthew 5:4',
    text: 'Blessed are those who mourn, for they will be comforted.',
    tags: ['grief', 'comfort', 'blessing'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/matt_5_4.mp3?alt=media&token=368c6aca-2685-4e86-ae78-9118bd1d7200',
    duration: 8,
  },
  {
    id: 'rev_21_4',
    reference: 'Revelation 21:4',
    text: 'He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away.',
    tags: ['grief', 'hope', 'eternity'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/rev_21_4.mp3?alt=media&token=fec1ea39-7bc5-4300-aea1-72a59b63a4bd',
    duration: 16,
  },
  {
    id: 'ps_30_5',
    reference: 'Psalm 30:5',
    text: 'Weeping may stay for the night, but rejoicing comes in the morning.',
    tags: ['grief', 'sadness', 'hope', 'joy', 'encouragement'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_30_5.mp3?alt=media&token=c06ac323-7959-4810-8e2d-bca730f13c72',
    duration: 9,
  },
  {
    id: '2cor_1_3-4',
    reference: '2 Corinthians 1:3-4',
    text: 'Praise be to the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort, who comforts us in all our troubles.',
    tags: ['grief', 'comfort', 'compassion', 'sadness'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/2cor_1_3-4.mp3?alt=media&token=150ab3be-478a-416d-a139-ec2b7e4ac1b3',
    duration: 16,
  },
  {
    id: 'john_16_22',
    reference: 'John 16:22',
    text: 'Now is your time of grief, but I will see you again and you will rejoice, and no one will take away your joy.',
    tags: ['grief', 'joy', 'hope', 'comfort'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/john_16_22.mp3?alt=media&token=37177785-4b65-4322-a75c-d2c6ff8b7f78',
    duration: 13,
  },
  
  // Depression
  {
    id: 'ps_42_11',
    reference: 'Psalm 42:11',
    text: 'Why, my soul, are you downcast? Why so disturbed within me? Put your hope in God, for I will yet praise him, my Savior and my God.',
    tags: ['depression', 'hope', 'praise'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_42_11.mp3?alt=media&token=660ab4d6-0b75-4484-93ae-5767c9f90fa2',
    duration: 14,
  },
  {
    id: 'ps_147_3',
    reference: 'Psalm 147:3',
    text: 'He heals the brokenhearted and binds up their wounds.',
    tags: ['depression', 'healing', 'comfort'],
    category: 'health',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_147_3.mp3?alt=media&token=103d49f2-e2ce-4995-9244-099146f6b747',
    duration: 8,
  },
  {
    id: 'ps_143_7-8',
    reference: 'Psalm 143:7-8',
    text: 'Answer me quickly, Lord; my spirit fails. Do not hide your face from me or I will be like those who go down to the pit. Let the morning bring me word of your unfailing love, for I have put my trust in you. Show me the way I should go, for to you I entrust my life.',
    tags: ['depression', 'hope', 'trust', 'guidance'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_143_7-8.mp3?alt=media&token=1ac0a8cb-c436-432f-bf8e-b3719fc458be',
    duration: 20,
  },
  
  // Anger
  {
    id: 'eph_4_26',
    reference: 'Ephesians 4:26-27',
    text: 'In your anger do not sin. Do not let the sun go down while you are still angry, and do not give the devil a foothold.',
    tags: ['anger', 'self-control', 'wisdom'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/eph_4_32.mp3?alt=media&token=ab2a9fab-0207-4dca-a8de-efcf1bea3b1b',
    duration: 14,
  },
  {
    id: 'prov_15_1',
    reference: 'Proverbs 15:1',
    text: 'A gentle answer turns away wrath, but a harsh word stirs up anger.',
    tags: ['anger', 'peace', 'wisdom'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_15_1.mp3?alt=media&token=81b2dc2c-26b9-4259-85cc-1993032cc7a8',
    duration: 9,
  },
  
  // Health
  {
    id: 'jer_17_14',
    reference: 'Jeremiah 17:14',
    text: 'Heal me, Lord, and I will be healed; save me and I will be saved, for you are the one I praise.',
    tags: ['health', 'healing', 'praise'],
    category: 'health',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/jer_17_14.mp3?alt=media&token=aa7429e7-f80c-4407-9b19-040fdeaec4ed',
    duration: 11,
  },
  {
    id: 'ps_103_2-3',
    reference: 'Psalm 103:2-3',
    text: 'Praise the Lord, my soul, and forget not all his benefits—who forgives all your sins and heals all your diseases.',
    tags: ['health', 'healing', 'forgiveness'],
    category: 'health',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_103_2-3.mp3?alt=media&token=a2d3cf21-70b1-44a1-b69c-c8dfb72323b0',
    duration: 13,
  },
  {
    id: 'isa_53_5',
    reference: 'Isaiah 53:5',
    text: 'But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed.',
    tags: ['health', 'healing', 'salvation'],
    category: 'health',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/isa_53_5.mp3?alt=media&token=d35f1a79-463d-4b5e-8fc3-3070e424a79f',
    duration: 18,
  },
  
  // Finances
  {
    id: 'phil_4_19',
    reference: 'Philippians 4:19',
    text: 'And my God will meet all your needs according to the riches of his glory in Christ Jesus.',
    tags: ['finances', 'provision', 'trust'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/phil_4_19.mp3?alt=media&token=3edaeb16-52dd-46e3-a90a-c7bc9ba2894d',
    duration: 11,
  },
  {
    id: 'matt_6_33',
    reference: 'Matthew 6:33',
    text: 'But seek first his kingdom and his righteousness, and all these things will be given to you as well.',
    tags: ['finances', 'priorities', 'provision'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/matt_6_31-33.mp3?alt=media&token=33b4bc83-5daa-4f9c-ad09-5454583fbb8d',
    duration: 12,
  },
  {
    id: 'prov_3_9-10',
    reference: 'Proverbs 3:9-10',
    text: 'Honor the Lord with your wealth, with the firstfruits of all your crops; then your barns will be filled to overflowing.',
    tags: ['finances', 'generosity', 'blessing'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_3_9-10.mp3?alt=media&token=21be2e59-d13e-42fd-ade1-1d55fa0d4c37',
    duration: 14,
  },
  
  // Work
  {
    id: 'col_3_23',
    reference: 'Colossians 3:23',
    text: 'Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.',
    tags: ['work', 'purpose', 'diligence'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/col_3_23.mp3?alt=media&token=b774aac7-cbe2-47e1-88f1-a4bbd4b2c694',
    duration: 12,
  },
  {
    id: 'prov_16_3',
    reference: 'Proverbs 16:3',
    text: 'Commit to the Lord whatever you do, and he will establish your plans.',
    tags: ['work', 'guidance', 'trust'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_16_3.mp3?alt=media&token=b368e99d-5354-421a-b0b6-8f7c58420b96',
    duration: 9,
  },
  
  // Faith
  {
    id: 'heb_11_1',
    reference: 'Hebrews 11:1',
    text: 'Now faith is confidence in what we hope for and assurance about what we do not see.',
    tags: ['faith', 'hope', 'trust'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/heb_11_1.mp3?alt=media&token=9ee984b8-e3d5-4ff2-a524-21d95d5b545d',
    duration: 10,
  },
  {
    id: 'mark_11_24',
    reference: 'Mark 11:24',
    text: 'Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours.',
    tags: ['faith', 'prayer', 'belief'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/mark_11_22.mp3?alt=media&token=a417dbee-498c-4c5d-a1c6-fc204d4a1da7',
    duration: 12,
  },
  {
    id: 'rom_10_17',
    reference: 'Romans 10:17',
    text: 'Consequently, faith comes from hearing the message, and the message is heard through the word about Christ.',
    tags: ['faith', 'word', 'growth'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/rom_10_17.mp3?alt=media&token=75259687-aa03-46a5-8c81-d5c8a0d79183',
    duration: 11,
  },
  
  // Strength
  {
    id: 'isa_40_31',
    reference: 'Isaiah 40:31',
    text: 'But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.',
    tags: ['strength', 'hope', 'endurance'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/isa_40_31.mp3?alt=media&token=55feebd5-52c4-488c-8ee2-25ee829ff27e',
    duration: 17,
  },
  {
    id: 'phil_4_13',
    reference: 'Philippians 4:13',
    text: 'I can do all this through him who gives me strength.',
    tags: ['strength', 'empowerment', 'faith'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/phil_4_13.mp3?alt=media&token=13af0ad4-bd58-4f61-b4ca-145d21bbe5ba',
    duration: 7,
  },
  {
    id: 'ps_46_1',
    reference: 'Psalm 46:1',
    text: 'God is our refuge and strength, an ever-present help in trouble.',
    tags: ['strength', 'refuge', 'help'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_46_1.mp3?alt=media&token=d9d4537a-56a4-47bf-b232-7120937aa7e0',
    duration: 9,
  },
  
  // Peace
  {
    id: 'john_14_27',
    reference: 'John 14:27',
    text: 'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.',
    tags: ['peace', 'comfort', 'trust'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/john_14_27.mp3?alt=media&token=1e123829-e070-4b4d-80a3-54580852399f',
    duration: 16,
  },
  {
    id: 'isa_26_3',
    reference: 'Isaiah 26:3',
    text: 'You will keep in perfect peace those whose minds are steadfast, because they trust in you.',
    tags: ['peace', 'trust', 'mind'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/isa_26_3.mp3?alt=media&token=3b679888-276e-4612-a497-ff738ad3f569',
    duration: 11,
  },
  
  // Guidance
  {
    id: 'prov_3_5-6',
    reference: 'Proverbs 3:5-6',
    text: 'Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.',
    tags: ['guidance', 'trust', 'wisdom'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_3_5-6.mp3?alt=media&token=1b2a98a2-0bd6-492e-a0e1-beb2cb354e54',
    duration: 15,
  },
  {
    id: 'ps_32_8',
    reference: 'Psalm 32:8',
    text: 'I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.',
    tags: ['guidance', 'wisdom', 'teaching'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_32_8.mp3?alt=media&token=d0b7a605-b786-400d-ab40-4eccb6eb238a',
    duration: 12,
  },
  {
    id: 'james_1_5',
    reference: 'James 1:5',
    text: 'If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.',
    tags: ['guidance', 'wisdom', 'prayer'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/james_1_5.mp3?alt=media&token=d41ff038-c3e3-49c3-9b1c-4612e73e247b',
    duration: 13,
  },
  
  // Purpose
  {
    id: 'jer_29_11',
    reference: 'Jeremiah 29:11',
    text: 'For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.',
    tags: ['purpose', 'hope', 'future'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/jer_29_11.mp3?alt=media&token=5a9bd3d8-ea6a-4308-bbbc-22f9ed6cbcf8',
    duration: 16,
  },
  {
    id: 'eph_2_10',
    reference: 'Ephesians 2:10',
    text: "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.",
    tags: ['purpose', 'identity', 'calling'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/eph_2_10.mp3?alt=media&token=5b7c87ff-086b-4130-bfe9-cbb7da520f6c',
    duration: 13,
  },
  
  // Forgiveness
  {
    id: '1_john_1_9',
    reference: '1 John 1:9',
    text: 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.',
    tags: ['forgiveness', 'confession', 'grace'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/1john_1_9.mp3?alt=media&token=4f00a16a-b9f3-4d6a-8b3b-6a0030a602cd',
    duration: 13,
  },
  {
    id: 'col_3_13',
    reference: 'Colossians 3:13',
    text: 'Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you.',
    tags: ['forgiveness', 'relationships', 'grace'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/col_3_13.mp3?alt=media&token=9405ac73-306f-42e8-8f85-8f64ade4707c',
    duration: 14,
  },
  
  // Marriage & Family
  {
    id: 'eph_5_25',
    reference: 'Ephesians 5:25',
    text: 'Husbands, love your wives, just as Christ loved the church and gave himself up for her.',
    tags: ['marriage', 'love', 'sacrifice'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/eph_5_25.mp3?alt=media&token=fa368aa9-4815-43df-bdfa-0300bac175f6',
    duration: 11,
  },
  {
    id: 'prov_22_6',
    reference: 'Proverbs 22:6',
    text: 'Start children off on the way they should go, and even when they are old they will not turn from it.',
    tags: ['parenting', 'family', 'wisdom'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_22_6.mp3?alt=media&token=8a1c8a8f-7a70-4032-a578-1260dbd9987e',
    duration: 11,
  },
  
  // Gratitude
  {
    id: '1_thess_5_18',
    reference: '1 Thessalonians 5:18',
    text: "Give thanks in all circumstances; for this is God's will for you in Christ Jesus.",
    tags: ['gratitude', 'thankfulness', 'joy'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/1thess_4_11-12.mp3?alt=media&token=f0f9f50c-edf9-420a-b38b-558d248e7a49',
    duration: 10,
  },
  {
    id: 'ps_100_4',
    reference: 'Psalm 100:4',
    text: 'Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name.',
    tags: ['gratitude', 'praise', 'worship'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_103_12.mp3?alt=media&token=3e7b06ca-5872-4754-b60f-e493a25fb44b',
    duration: 11,
  },
  
  // Doubt
  {
    id: 'mark_9_24',
    reference: 'Mark 9:24',
    text: 'Immediately the boy\'s father exclaimed, "I do believe; help me overcome my unbelief!"',
    tags: ['doubt', 'faith', 'honesty'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/john_20_29.mp3?alt=media&token=72bd5358-e62e-44f5-84de-c0d3c4d34f81',
    duration: 10,
  },
  
  // Loneliness
  {
    id: 'deut_31_6',
    reference: 'Deuteronomy 31:6',
    text: 'Be strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you; he will never leave you nor forsake you.',
    tags: ['loneliness', 'courage', 'presence'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/deut_31_6.mp3?alt=media&token=3b6c79f8-e56c-431e-a4ef-cc03fc48a5e4',
    duration: 18,
  },
  {
    id: 'matt_28_20',
    reference: 'Matthew 28:20',
    text: 'And surely I am with you always, to the very end of the age.',
    tags: ['loneliness', 'presence', 'comfort'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/matt_11_28.mp3?alt=media&token=b70054d3-a4e7-4df7-9d23-f975300a8a3c',
    duration: 8,
  },
  
  // Stress
  {
    id: 'matt_11_28-30',
    reference: 'Matthew 11:28-30',
    text: 'Come to me, all you who are weary and burdened, and I will give you rest. Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls. For my yoke is easy and my burden is light.',
    tags: ['stress', 'rest', 'peace'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/matt_11_28.mp3?alt=media&token=b70054d3-a4e7-4df7-9d23-f975300a8a3c',
    duration: 22,
  },
  
  // Addiction
  {
    id: 'gal_5_1',
    reference: 'Galatians 5:1',
    text: 'It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.',
    tags: ['addiction', 'freedom', 'strength'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/gal_5_1.mp3?alt=media&token=bd532064-3111-4bbe-ab49-7f0748baf527',
    duration: 13,
  },
  {
    id: '2_cor_5_17',
    reference: '2 Corinthians 5:17',
    text: 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!',
    tags: ['addiction', 'renewal', 'transformation'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/2cor_5_17.mp3?alt=media&token=04200d2c-2cb9-4f7a-9cf3-f77aa5c03414',
    duration: 11,
  },
  {
    id: 'isa_61_1',
    reference: 'Isaiah 61:1',
    text: 'The Spirit of the Sovereign Lord is on me, because the Lord has anointed me to proclaim good news to the poor. He has sent me to bind up the brokenhearted, to proclaim freedom for the captives and release from darkness for the prisoners.',
    tags: ['addiction', 'freedom', 'deliverance', 'healing', 'hope'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/isa_61_1.mp3?alt=media&token=730789aa-4d5b-4923-ac73-9b448522674b',
    duration: 20,
  },
  
  // Conflict
  {
    id: 'rom_12_18',
    reference: 'Romans 12:18',
    text: 'If it is possible, as far as it depends on you, live at peace with everyone.',
    tags: ['conflict', 'peace', 'relationships'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/rom_12_18.mp3?alt=media&token=edf4bbcc-b709-4fff-8c69-7e3750561f44',
    duration: 10,
  },
  
  // Temptation
  {
    id: '1cor_10_13',
    reference: '1 Corinthians 10:13',
    text: 'No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can endure it.',
    tags: ['temptation', 'strength', 'faith', 'endurance'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/1cor_10_13.mp3?alt=media&token=13c24ac8-1a17-4fef-9919-45e63f3dd143',
    duration: 22,
  },
  {
    id: '1cor_16_13',
    reference: '1 Corinthians 16:13',
    text: 'Be on your guard; stand firm in the faith; be courageous; be strong.',
    tags: ['courage', 'strength', 'faith'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/1cor_16_13.mp3?alt=media&token=bad14337-432e-4ce7-8440-3dfbc5064ced',
    duration: 9,
  },
  {
    id: '1john_4_8',
    reference: '1 John 4:8',
    text: 'Whoever does not love does not know God, because God is love.',
    tags: ['love', 'faith', 'identity'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/1john_4_8.mp3?alt=media&token=9c6b9f0c-1a0b-4738-a709-24be02fd156a',
    duration: 8,
  },
  {
    id: '1pet_4_8',
    reference: '1 Peter 4:8',
    text: 'Above all, love each other deeply, because love covers over a multitude of sins.',
    tags: ['love', 'forgiveness', 'relationships'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/1pet_4_8.mp3?alt=media&token=84934f2e-0342-40f1-89f9-16aabb02adaa',
    duration: 10,
  },
  {
    id: '1tim_6_10',
    reference: '1 Timothy 6:10',
    text: 'For the love of money is a root of all kinds of evil. Some people, eager for money, have wandered from the faith and pierced themselves with many griefs.',
    tags: ['finances', 'wisdom', 'temptation'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/1tim_6_10.mp3?alt=media&token=f1cdc44d-5656-417c-b250-da467277fc57',
    duration: 16,
  },
  {
    id: '2cor_12_9',
    reference: '2 Corinthians 12:9',
    text: 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly about my weaknesses, so that Christ\'s power may rest on me.',
    tags: ['grace', 'strength', 'weakness'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/2cor_12_9.mp3?alt=media&token=927d139d-0ffa-445a-a1c4-63dff8a28574',
    duration: 18,
  },
  {
    id: '2cor_4_16-17',
    reference: '2 Corinthians 4:16-17',
    text: 'Therefore we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day. For our light and momentary troubles are achieving for us an eternal glory that far outweighs them all.',
    tags: ['hope', 'perseverance', 'renewal'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/2cor_4_16-17.mp3?alt=media&token=f650d526-753f-4885-b6bc-6807fd46c324',
    duration: 20,
  },
  {
    id: '2cor_5_7',
    reference: '2 Corinthians 5:7',
    text: 'For we live by faith, not by sight.',
    tags: ['faith', 'trust', 'belief'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/2cor_5_7.mp3?alt=media&token=aeebffe2-36da-4eb2-99e9-4442e748aa16',
    duration: 6,
  },
  {
    id: '2cor_9_8',
    reference: '2 Corinthians 9:8',
    text: 'And God is able to bless you abundantly, so that in all things at all times, having all that you need, you will abound in every good work.',
    tags: ['blessing', 'provision', 'generosity'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/2cor_9_8.mp3?alt=media&token=33fd893a-736a-4d33-b954-d4a750f21f10',
    duration: 14,
  },
  {
    id: '2thess_3_10',
    reference: '2 Thessalonians 3:10',
    text: 'For even when we were with you, we gave you this rule: "The one who is unwilling to work shall not eat."',
    tags: ['work', 'responsibility', 'discipline'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/2thess_3_10.mp3?alt=media&token=360b8500-9839-4269-a65e-afd9e2abab55',
    duration: 11,
  },
  {
    id: '2thess_3_5',
    reference: '2 Thessalonians 3:5',
    text: 'May the Lord direct your hearts into God\'s love and Christ\'s perseverance.',
    tags: ['love', 'perseverance', 'guidance'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/2thess_3_5.mp3?alt=media&token=c9466deb-22b8-4438-a4f1-e2f82820ba92',
    duration: 8,
  },
  {
    id: '3john_1_2',
    reference: '3 John 1:2',
    text: 'Dear friend, I pray that you may enjoy good health and that all may go well with you, even as your soul is getting along well.',
    tags: ['health', 'blessing', 'prayer'],
    category: 'health',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/3john_1_2.mp3?alt=media&token=c1796019-7c48-496f-8163-efe759597463',
    duration: 13,
  },
  {
    id: 'acts_3_19',
    reference: 'Acts 3:19',
    text: 'Repent, then, and turn to God, so that your sins may be wiped out, that times of refreshing may come from the Lord.',
    tags: ['repentance', 'forgiveness', 'renewal'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/acts_3_19.mp3?alt=media&token=9a052a65-c614-41ce-ac2a-fbb12be8e325',
    duration: 12,
  },
  {
    id: 'col_3_15',
    reference: 'Colossians 3:15',
    text: 'Let the peace of Christ rule in your hearts, since as members of one body you were called to peace. And be thankful.',
    tags: ['peace', 'gratitude', 'unity'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/col_3_15.mp3?alt=media&token=20821b64-6245-4fda-b2f6-c3372681dd31',
    duration: 12,
  },
  {
    id: 'col_3_21',
    reference: 'Colossians 3:21',
    text: 'Fathers, do not embitter your children, or they will become discouraged.',
    tags: ['parenting', 'family', 'wisdom'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/col_3_21.mp3?alt=media&token=ec9c34af-055b-4af0-b0c3-83594c07a041',
    duration: 8,
  },
  {
    id: 'deut_6_6-7',
    reference: 'Deuteronomy 6:6-7',
    text: 'These commandments that I give you today are to be on your hearts. Impress them on your children. Talk about them when you sit at home and when you walk along the road, when you lie down and when you get up.',
    tags: ['parenting', 'faith', 'teaching'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/deut_6_6-7.mp3?alt=media&token=a77612da-9b95-47b3-ad9e-c4976087c654',
    duration: 20,
  },
  {
    id: 'eccl_9_10',
    reference: 'Ecclesiastes 9:10',
    text: 'Whatever your hand finds to do, do it with all your might, for in the realm of the dead, where you are going, there is neither working nor planning nor knowledge nor wisdom.',
    tags: ['work', 'diligence', 'purpose'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/eccl_9_10.mp3?alt=media&token=d60da1a9-2123-46dc-90ed-9459d2277888',
    duration: 18,
  },
  {
    id: 'eph_6_10',
    reference: 'Ephesians 6:10',
    text: 'Finally, be strong in the Lord and in his mighty power.',
    tags: ['strength', 'power', 'faith'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/eph_6_10.mp3?alt=media&token=3942aade-ce62-428a-8ae7-062b30a1cd32',
    duration: 8,
  },
  {
    id: 'eph_6_4',
    reference: 'Ephesians 6:4',
    text: 'Fathers, do not exasperate your children; instead, bring them up in the training and instruction of the Lord.',
    tags: ['parenting', 'family', 'discipline'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/eph_6_4.mp3?alt=media&token=c4a4713a-7660-4de9-bcd6-daef2d543364',
    duration: 11,
  },
  {
    id: 'ex_15_26',
    reference: 'Exodus 15:26',
    text: 'He said, "If you listen carefully to the Lord your God and do what is right in his eyes, if you pay attention to his commands and keep all his decrees, I will not bring on you any of the diseases I brought on the Egyptians, for I am the Lord, who heals you."',
    tags: ['health', 'healing', 'obedience'],
    category: 'health',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ex_15_26.mp3?alt=media&token=573026ab-0609-416f-8808-e1bea00d5e28',
    duration: 25,
  },
  {
    id: 'gal_2_20',
    reference: 'Galatians 2:20',
    text: 'I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me.',
    tags: ['faith', 'identity', 'sacrifice'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/gal_2_20.mp3?alt=media&token=a1dce39f-3c57-460f-8b53-ff66adf7289f',
    duration: 18,
  },
  {
    id: 'gal_6_9',
    reference: 'Galatians 6:9',
    text: 'Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.',
    tags: ['perseverance', 'hope', 'reward'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/gal_6_9.mp3?alt=media&token=00f85cc4-b8c4-426e-b868-87e925924b8c',
    duration: 13,
  },
  {
    id: 'hab_3_19',
    reference: 'Habakkuk 3:19',
    text: 'The Sovereign Lord is my strength; he makes my feet like the feet of a deer, he enables me to tread on the heights.',
    tags: ['strength', 'confidence', 'empowerment'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/hab_3_19.mp3?alt=media&token=b4f2542f-e461-4ae4-8b7b-f62e8d5d337c',
    duration: 12,
  },
  {
    id: 'heb_10_36',
    reference: 'Hebrews 10:36',
    text: 'You need to persevere so that when you have done the will of God, you will receive what he has promised.',
    tags: ['perseverance', 'patience', 'promise'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/heb_10_36.mp3?alt=media&token=3590d335-cf32-47b3-a222-c0129b011673',
    duration: 12,
  },
  {
    id: 'heb_11_6',
    reference: 'Hebrews 11:6',
    text: 'And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him.',
    tags: ['faith', 'belief', 'seeking'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/heb_11_6.mp3?alt=media&token=a3c8f371-88eb-4685-8dc2-5e4dc10661be',
    duration: 15,
  },
  {
    id: 'heb_13_5',
    reference: 'Hebrews 13:5',
    text: 'Keep your lives free from the love of money and be content with what you have, because God has said, "Never will I leave you; never will I forsake you."',
    tags: ['contentment', 'finances', 'trust'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/heb_13_5.mp3?alt=media&token=ae7f7eee-b97d-4eb1-8244-ce831fb5888f',
    duration: 16,
  },
  
  // Love
  {
    id: '1cor_13_4-7',
    reference: '1 Corinthians 13:4-7',
    text: 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs. Love does not delight in evil but rejoices with the truth. It always protects, always trusts, always hopes, always perseveres.',
    tags: ['love', 'relationships', 'kindness', 'patience'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/1cor_13_4-7.mp3?alt=media&token=7dd54de5-774d-490b-81c1-607326b69306',
    duration: 35,
  },
  
  // Identity
  {
    id: '1john_3_1',
    reference: '1 John 3:1',
    text: 'See what great love the Father has lavished on us, that we should be called children of God! And that is what we are! The reason the world does not know us is that it did not know him.',
    tags: ['love', 'identity', 'faith', 'encouragement'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/1john_3_1.mp3?alt=media&token=69918985-d360-440e-b46b-e0ba587b1cbc',
    duration: 18,
  },
  {
    id: 'isa_12_2',
    reference: 'Isaiah 12:2',
    text: 'Surely God is my salvation; I will trust and not be afraid. The Lord, the Lord himself, is my strength and my defense; he has become my salvation.',
    tags: ['salvation', 'trust', 'strength'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/isa_12_2.mp3?alt=media&token=5330454a-1213-426b-9deb-69c259ccda25',
    duration: 14,
  },
  {
    id: 'isa_30_21',
    reference: 'Isaiah 30:21',
    text: 'Whether you turn to the right or to the left, your ears will hear a voice behind you, saying, "This is the way; walk in it."',
    tags: ['guidance', 'direction', 'wisdom'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/isa_30_21.mp3?alt=media&token=2815ac05-2d76-4204-b251-0cb20224435b',
    duration: 12,
  },
  {
    id: 'isa_35_4',
    reference: 'Isaiah 35:4',
    text: 'Say to those with fearful hearts, "Be strong, do not fear; your God will come, he will come with vengeance; with divine retribution he will come to save you."',
    tags: ['courage', 'fear', 'salvation'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/isa_35_4.mp3?alt=media&token=3d6d80b2-54df-4a97-80f8-df5693544d17',
    duration: 15,
  },
  {
    id: 'isa_40_28-29',
    reference: 'Isaiah 40:28-29',
    text: 'Do you not know? Have you not heard? The Lord is the everlasting God, the Creator of the ends of the earth. He will not grow tired or weary, and his understanding no one can fathom. He gives strength to the weary and increases the power of the weak.',
    tags: ['strength', 'endurance', 'power'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/isa_40_28-29.mp3?alt=media&token=15feb18d-f32c-4514-ad2b-1d0ba3df0ef5',
    duration: 20,
  },
  {
    id: 'isa_43_1',
    reference: 'Isaiah 43:1',
    text: 'But now, this is what the Lord says—he who created you, Jacob, he who formed you, Israel: "Do not fear, for I have redeemed you; I have summoned you by name; you are mine."',
    tags: ['identity', 'fear', 'redemption'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/isa_43_1.mp3?alt=media&token=5b4c978c-17f7-423d-a66b-05b53810a640',
    duration: 16,
  },
  {
    id: 'isa_43_25',
    reference: 'Isaiah 43:25',
    text: 'I, even I, am he who blots out your transgressions, for my own sake, and remembers your sins no more.',
    tags: ['forgiveness', 'grace', 'redemption'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/isa_43_25.mp3?alt=media&token=bc595d57-fb7a-468f-bf9a-dd2963c0bd53',
    duration: 12,
  },
  {
    id: 'isa_61_3',
    reference: 'Isaiah 61:3',
    text: 'To provide for those who grieve in Zion—to bestow on them a crown of beauty instead of ashes, the oil of joy instead of mourning, and a garment of praise instead of a spirit of despair.',
    tags: ['grief', 'joy', 'transformation'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/isa_61_3.mp3?alt=media&token=837ab240-f53e-4d16-9dc1-d8f2a6866c47',
    duration: 18,
  },
  {
    id: 'james_1_2-4',
    reference: 'James 1:2-4',
    text: 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance. Let perseverance finish its work so that you may be mature and complete, not lacking anything.',
    tags: ['trials', 'perseverance', 'joy'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/james_1_2-4.mp3?alt=media&token=be20bebd-9e83-4f42-8c19-d0b4b0ebc524',
    duration: 18,
  },
  {
    id: 'james_4_7',
    reference: 'James 4:7',
    text: 'Submit yourselves, then, to God. Resist the devil, and he will flee from you.',
    tags: ['temptation', 'spiritual warfare', 'strength'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/james_4_7.mp3?alt=media&token=f25ee467-d042-4118-888b-aabffb8a20e8',
    duration: 9,
  },
  {
    id: 'james_5_15',
    reference: 'James 5:15',
    text: 'And the prayer offered in faith will make the sick person well; the Lord will raise them up. If they have sinned, they will be forgiven.',
    tags: ['healing', 'prayer', 'faith'],
    category: 'health',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/james_5_15.mp3?alt=media&token=c6fef463-1837-4b4f-a58e-1ffc722f2cc8',
    duration: 13,
  },
  {
    id: 'john_15_13',
    reference: 'John 15:13',
    text: 'Greater love has no one than this: to lay down one\'s life for one\'s friends.',
    tags: ['love', 'sacrifice', 'friendship'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/john_15_13.mp3?alt=media&token=49afb0ab-b878-432c-a5d3-c48ed2a54405',
    duration: 9,
  },
  {
    id: 'john_16_13',
    reference: 'John 16:13',
    text: 'But when he, the Spirit of truth, comes, he will guide you into all the truth. He will not speak on his own; he will speak only what he hears, and he will tell you what is yet to come.',
    tags: ['guidance', 'truth', 'spirit'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/john_16_13.mp3?alt=media&token=40422c31-6ed3-40f7-9c86-66cb31aa848a',
    duration: 17,
  },
  {
    id: 'john_3_16',
    reference: 'John 3:16',
    text: 'For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.',
    tags: ['love', 'salvation', 'faith'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/john_3_16.mp3?alt=media&token=2f2160ac-7c93-45f5-b7c2-f360c04658a8',
    duration: 13,
  },
  {
    id: 'john_8_36',
    reference: 'John 8:36',
    text: 'So if the Son sets you free, you will be free indeed.',
    tags: ['freedom', 'liberation', 'faith'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/john_8_36.mp3?alt=media&token=6f2e002d-3a69-4ec8-846f-16931101f0b7',
    duration: 7,
  },
  {
    id: 'josh_1_9',
    reference: 'Joshua 1:9',
    text: 'Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.',
    tags: ['courage', 'strength', 'fear'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/josh_1_9.mp3?alt=media&token=741d1d56-1d32-47d0-853c-ad9a0220a71e',
    duration: 15,
  },
  {
    id: 'lam_3_22-23',
    reference: 'Lamentations 3:22-23',
    text: 'Because of the Lord\'s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.',
    tags: ['love', 'faithfulness', 'hope'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/lam_3_22-23.mp3?alt=media&token=fbc2fa6e-e805-4537-a7b2-91d63f80cf05',
    duration: 14,
  },
  {
    id: 'luke_6_38',
    reference: 'Luke 6:38',
    text: 'Give, and it will be given to you. A good measure, pressed down, shaken together and running over, will be poured into your lap. For with the measure you use, it will be measured to you.',
    tags: ['generosity', 'giving', 'blessing'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/luke_6_38.mp3?alt=media&token=02117149-c544-4fd0-9fc9-981ca945dada',
    duration: 16,
  },
  {
    id: 'mal_3_10',
    reference: 'Malachi 3:10',
    text: 'Bring the whole tithe into the storehouse, that there may be food in my house. Test me in this, says the Lord Almighty, and see if I will not throw open the floodgates of heaven and pour out so much blessing that there will not be room enough to store it.',
    tags: ['generosity', 'blessing', 'finances'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/mal_3_10.mp3?alt=media&token=4f41fa24-179e-4f18-b41d-58f05d024fb2',
    duration: 22,
  },
  {
    id: 'mal_4_2',
    reference: 'Malachi 4:2',
    text: 'But for you who revere my name, the sun of righteousness will rise with healing in its rays. And you will go out and frolic like well-fed calves.',
    tags: ['healing', 'joy', 'hope'],
    category: 'health',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/mal_4_2.mp3?alt=media&token=9c9288dd-721c-4eeb-bb2f-6d6adf8136a1',
    duration: 13,
  },
  {
    id: 'matt_17_20',
    reference: 'Matthew 17:20',
    text: 'Truly I tell you, if you have faith as small as a mustard seed, you can say to this mountain, "Move from here to there," and it will move. Nothing will be impossible for you.',
    tags: ['faith', 'belief', 'power'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/matt_17_20.mp3?alt=media&token=902d3559-76b3-4481-a5e2-04562054a417',
    duration: 16,
  },
  {
    id: 'matt_6_14',
    reference: 'Matthew 6:14',
    text: 'For if you forgive other people when they sin against you, your heavenly Father will also forgive you.',
    tags: ['forgiveness', 'grace', 'relationships'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/matt_6_14.mp3?alt=media&token=539e3f0c-8c59-4359-a264-8fd6a7c0fce4',
    duration: 11,
  },
  {
    id: 'mic_7_18-19',
    reference: 'Micah 7:18-19',
    text: 'Who is a God like you, who pardons sin and forgives the transgression of the remnant of his inheritance? You do not stay angry forever but delight to show mercy. You will again have compassion on us; you will tread our sins underfoot and hurl all our iniquities into the depths of the sea.',
    tags: ['forgiveness', 'mercy', 'grace'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/mic_7_18-19.mp3?alt=media&token=5918dad1-5906-477d-a6c9-734a687869a6',
    duration: 22,
  },
  {
    id: 'neh_8_10',
    reference: 'Nehemiah 8:10',
    text: 'Do not grieve, for the joy of the Lord is your strength.',
    tags: ['joy', 'strength', 'encouragement'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/neh_8_10.mp3?alt=media&token=42c8e082-5f7e-4962-a73a-cafcfe455b08',
    duration: 7,
  },
  {
    id: 'phil_4_8',
    reference: 'Philippians 4:8',
    text: 'Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things.',
    tags: ['mind', 'thinking', 'wisdom'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/phil_4_8.mp3?alt=media&token=5e1aa41d-28b4-4b5b-b6de-4cf36cf03c52',
    duration: 18,
  },
  {
    id: 'prov_11_14',
    reference: 'Proverbs 11:14',
    text: 'For lack of guidance a nation falls, but victory is won through many advisers.',
    tags: ['wisdom', 'guidance', 'counsel'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_11_14.mp3?alt=media&token=aa911073-d80e-451b-8186-059541fa0a99',
    duration: 10,
  },
  {
    id: 'prov_12_11',
    reference: 'Proverbs 12:11',
    text: 'Those who work their land will have abundant food, but those who chase fantasies have no sense.',
    tags: ['work', 'diligence', 'wisdom'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_12_11.mp3?alt=media&token=fd380f5d-8d7f-453d-8365-b5b0a7c3f555',
    duration: 10,
  },
  {
    id: 'prov_12_25',
    reference: 'Proverbs 12:25',
    text: 'Anxiety weighs down the heart, but a kind word cheers it up.',
    tags: ['anxiety', 'encouragement', 'kindness'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_12_25.mp3?alt=media&token=7a0f278c-d185-4ed3-853e-da7fed7acdcd',
    duration: 8,
  },
  {
    id: 'prov_13_11',
    reference: 'Proverbs 13:11',
    text: 'Dishonest money dwindles away, but whoever gathers money little by little makes it grow.',
    tags: ['finances', 'integrity', 'wisdom'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_13_11.mp3?alt=media&token=14ef811a-7a1e-4c6f-8ac6-ca3be69a47a2',
    duration: 10,
  },
  {
    id: 'prov_14_23',
    reference: 'Proverbs 14:23',
    text: 'All hard work brings a profit, but mere talk leads only to poverty.',
    tags: ['work', 'diligence', 'success'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_14_23.mp3?alt=media&token=5b2b507b-da65-4ecf-88cf-77e9dad8a07d',
    duration: 9,
  },
  {
    id: 'prov_16_9',
    reference: 'Proverbs 16:9',
    text: 'In their hearts humans plan their course, but the Lord establishes their steps.',
    tags: ['guidance', 'planning', 'trust'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_16_9.mp3?alt=media&token=976843c8-25f6-4d3a-86f2-61967af90c62',
    duration: 9,
  },
  {
    id: 'prov_17_22',
    reference: 'Proverbs 17:22',
    text: 'A cheerful heart is good medicine, but a crushed spirit dries up the bones.',
    tags: ['joy', 'health', 'emotions'],
    category: 'health',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_17_22.mp3?alt=media&token=6cbe7991-22a1-4967-927b-c6588376813d',
    duration: 9,
  },
  {
    id: 'prov_18_22',
    reference: 'Proverbs 18:22',
    text: 'He who finds a wife finds what is good and receives favor from the Lord.',
    tags: ['marriage', 'blessing', 'relationships'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_18_22.mp3?alt=media&token=0f292907-fa4e-45b7-af6f-4763e89b0c25',
    duration: 8,
  },
  {
    id: 'prov_22_29',
    reference: 'Proverbs 22:29',
    text: 'Do you see someone skilled in their work? They will serve before kings; they will not serve before officials of low rank.',
    tags: ['work', 'excellence', 'success'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_22_29.mp3?alt=media&token=c3dbd4be-cb06-4321-9994-4312a6bcab40',
    duration: 11,
  },
  {
    id: 'prov_22_7',
    reference: 'Proverbs 22:7',
    text: 'The rich rule over the poor, and the borrower is slave to the lender.',
    tags: ['finances', 'wisdom', 'debt'],
    category: 'life',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_22_7.mp3?alt=media&token=9ea49273-2113-41ef-b254-59d5ab71b143',
    duration: 8,
  },
  {
    id: 'prov_29_25',
    reference: 'Proverbs 29:25',
    text: 'Fear of man will prove to be a snare, but whoever trusts in the Lord is kept safe.',
    tags: ['fear', 'trust', 'safety'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_29_25.mp3?alt=media&token=4c00029d-2603-4ade-a1aa-9d9033e4a665',
    duration: 10,
  },
  {
    id: 'prov_2_6',
    reference: 'Proverbs 2:6',
    text: 'For the Lord gives wisdom; from his mouth come knowledge and understanding.',
    tags: ['wisdom', 'knowledge', 'understanding'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/prov_2_6.mp3?alt=media&token=ebaecc14-dad0-491d-ad55-33c7dc0e102e',
    duration: 9,
  },
  {
    id: 'ps_103_12',
    reference: 'Psalm 103:12',
    text: 'As far as the east is from the west, so far has he removed our transgressions from us.',
    tags: ['forgiveness', 'grace', 'mercy'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_103_12.mp3?alt=media&token=3e7b06ca-5872-4754-b60f-e493a25fb44b',
    duration: 9,
  },
  {
    id: 'ps_107_13-14',
    reference: 'Psalm 107:13-14',
    text: 'Then they cried to the Lord in their trouble, and he saved them from their distress. He brought them out of darkness, the utter darkness, and broke away their chains.',
    tags: ['deliverance', 'freedom', 'salvation'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_107_13-14.mp3?alt=media&token=149054bc-e88b-45af-83d9-1714e346c1b1',
    duration: 14,
  },
  {
    id: 'ps_118_6',
    reference: 'Psalm 118:6',
    text: 'The Lord is with me; I will not be afraid. What can mere mortals do to me?',
    tags: ['courage', 'fear', 'protection'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_118_6.mp3?alt=media&token=8efb4470-0ca4-41fa-b830-4fe2ef1694e9',
    duration: 9,
  },
  {
    id: 'ps_119_105',
    reference: 'Psalm 119:105',
    text: 'Your word is a lamp for my feet, a light on my path.',
    tags: ['guidance', 'word', 'direction'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_119_105.mp3?alt=media&token=4f3fddca-c7a8-4147-85d6-bbf9a9f48393',
    duration: 7,
  },
  {
    id: 'ps_119_50',
    reference: 'Psalm 119:50',
    text: 'My comfort in my suffering is this: Your promise preserves my life.',
    tags: ['comfort', 'suffering', 'promise'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_119_50.mp3?alt=media&token=75f803ab-1c93-4900-86f0-e425ffe8cf94',
    duration: 8,
  },
  {
    id: 'ps_127_3',
    reference: 'Psalm 127:3',
    text: 'Children are a heritage from the Lord, offspring a reward from him.',
    tags: ['parenting', 'blessing', 'family'],
    category: 'relationship',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_127_3.mp3?alt=media&token=5ecfe3d9-6f35-4831-bddb-21d94166a7fd',
    duration: 8,
  },
  {
    id: 'ps_18_32',
    reference: 'Psalm 18:32',
    text: 'It is God who arms me with strength and keeps my way secure.',
    tags: ['strength', 'security', 'protection'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_18_32.mp3?alt=media&token=bc7e43a2-025c-4010-9a9b-0435f80e2686',
    duration: 8,
  },
  {
    id: 'ps_25_4-5',
    reference: 'Psalm 25:4-5',
    text: 'Show me your ways, Lord, teach me your paths. Guide me in your truth and teach me, for you are God my Savior, and my hope is in you all day long.',
    tags: ['guidance', 'teaching', 'hope'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_25_4-5.mp3?alt=media&token=0a495117-5338-4df3-ae4f-6371b8b6a70e',
    duration: 14,
  },
  {
    id: 'ps_27_1',
    reference: 'Psalm 27:1',
    text: 'The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid?',
    tags: ['courage', 'fear', 'salvation'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_27_1.mp3?alt=media&token=79d55527-e6ff-4201-9c66-e65b81464b2f',
    duration: 11,
  },
  {
    id: 'ps_27_14',
    reference: 'Psalm 27:14',
    text: 'Wait for the Lord; be strong and take heart and wait for the Lord.',
    tags: ['patience', 'strength', 'hope'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_27_14.mp3?alt=media&token=297cd0e8-ceb1-4abb-94e9-e5b4238bf785',
    duration: 8,
  },
  {
    id: 'ps_28_7',
    reference: 'Psalm 28:7',
    text: 'The Lord is my strength and my shield; my heart trusts in him, and he helps me. My heart leaps for joy, and with my song I praise him.',
    tags: ['strength', 'trust', 'joy'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_28_7.mp3?alt=media&token=aedf5205-b87f-464e-ad26-0cebd8bbb933',
    duration: 13,
  },
  {
    id: 'ps_34_17-18',
    reference: 'Psalm 34:17-18',
    text: 'The righteous cry out, and the Lord hears them; he delivers them from all their troubles. The Lord is close to the brokenhearted and saves those who are crushed in spirit.',
    tags: ['comfort', 'deliverance', 'healing'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_34_17-18.mp3?alt=media&token=a01a7b30-5926-4efc-ae6f-b38a927dd95b',
    duration: 13,
  },
  {
    id: 'ps_41_3',
    reference: 'Psalm 41:3',
    text: 'The Lord sustains them on their sickbed and restores them from their bed of illness.',
    tags: ['healing', 'health', 'comfort'],
    category: 'health',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_41_3.mp3?alt=media&token=228ce331-8632-4145-95aa-24ea0b0e5990',
    duration: 9,
  },
  {
    id: 'ps_46_1-2',
    reference: 'Psalm 46:1-2',
    text: 'God is our refuge and strength, an ever-present help in trouble. Therefore we will not fear, though the earth give way and the mountains fall into the heart of the sea.',
    tags: ['strength', 'courage', 'trust'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_46_1-2.mp3?alt=media&token=37763499-87d5-4c0e-963a-cd76ed82e343',
    duration: 15,
  },
  {
    id: 'ps_55_22',
    reference: 'Psalm 55:22',
    text: 'Cast your cares on the Lord and he will sustain you; he will never let the righteous be shaken.',
    tags: ['trust', 'care', 'support'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_55_22.mp3?alt=media&token=078556f4-f259-4cf6-8580-02846ded7c60',
    duration: 10,
  },
  {
    id: 'ps_56_3',
    reference: 'Psalm 56:3',
    text: 'When I am afraid, I put my trust in you.',
    tags: ['fear', 'trust', 'faith'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_56_3.mp3?alt=media&token=3e340d1a-3293-4723-9d18-9a262a3a6540',
    duration: 6,
  },
  {
    id: 'ps_73_26',
    reference: 'Psalm 73:26',
    text: 'My flesh and my heart may fail, but God is the strength of my heart and my portion forever.',
    tags: ['strength', 'hope', 'endurance'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_73_26.mp3?alt=media&token=064c0ec0-01dd-4430-b737-214d9b9581d8',
    duration: 11,
  },
  {
    id: 'ps_86_5',
    reference: 'Psalm 86:5',
    text: 'You, Lord, are forgiving and good, abounding in love to all who call to you.',
    tags: ['forgiveness', 'love', 'grace'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_86_5.mp3?alt=media&token=a9606c28-2440-4526-b5c8-664d989df5ed',
    duration: 9,
  },
  {
    id: 'ps_88_1-2',
    reference: 'Psalm 88:1-2',
    text: 'Lord, you are the God who saves me; day and night I cry out to you. May my prayer come before you; turn your ear to my cry.',
    tags: ['prayer', 'help', 'salvation'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_88_1-2.mp3?alt=media&token=0075b8cf-7635-4f56-aba0-548a8837e601',
    duration: 12,
  },
  {
    id: 'ps_94_19',
    reference: 'Psalm 94:19',
    text: 'When anxiety was great within me, your consolation brought me joy.',
    tags: ['anxiety', 'comfort', 'joy'],
    category: 'emotion',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/ps_94_19.mp3?alt=media&token=9cc0f275-e5a4-44c5-8e25-22511dabc4cf',
    duration: 8,
  },
  {
    id: 'rom_15_13',
    reference: 'Romans 15:13',
    text: 'May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.',
    tags: ['hope', 'joy', 'peace'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/rom_15_13.mp3?alt=media&token=d17bbda8-b90d-4928-a733-23806f9d41bb',
    duration: 15,
  },
  {
    id: 'rom_5_3-4',
    reference: 'Romans 5:3-4',
    text: 'Not only so, but we also glory in our sufferings, because we know that suffering produces perseverance; perseverance, character; and character, hope.',
    tags: ['perseverance', 'hope', 'character'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/rom_5_3-4.mp3?alt=media&token=4c16726c-6902-4492-a2fc-aa5b1c1eb771',
    duration: 15,
  },
  {
    id: 'rom_5_8',
    reference: 'Romans 5:8',
    text: 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.',
    tags: ['love', 'grace', 'salvation'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/rom_5_8.mp3?alt=media&token=1bb3fc38-3301-4202-8343-eabaafc90607',
    duration: 11,
  },
  {
    id: 'rom_6_14',
    reference: 'Romans 6:14',
    text: 'For sin shall no longer be your master, because you are not under the law, but under grace.',
    tags: ['freedom', 'grace', 'victory'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/rom_6_14.mp3?alt=media&token=cc20c613-61aa-446b-80eb-426d45b11e24',
    duration: 10,
  },
  {
    id: 'rom_8_28',
    reference: 'Romans 8:28',
    text: 'And we know that in all things God works for the good of those who love him, who have been called according to his purpose.',
    tags: ['purpose', 'trust', 'hope'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/rom_8_28.mp3?alt=media&token=412d9d14-98c1-4620-aec5-c7c64e774b62',
    duration: 13,
  },
  {
    id: 'rom_8_38-39',
    reference: 'Romans 8:38-39',
    text: 'For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.',
    tags: ['love', 'security', 'faith'],
    category: 'spiritual',
    audioUrl: 'https://firebasestorage.googleapis.com/v0/b/admob-app-id-6381209483.firebasestorage.app/o/rom_8_38-39.mp3?alt=media&token=ae918d0e-16b9-4ec6-8c29-b432611eea73',
    duration: 22,
  },
];

export const getVersesByTopic = (topicId: string): Verse[] => {
  return VERSES.filter(verse => verse.tags.includes(topicId));
};

export const getVerseById = (id: string): Verse | undefined => {
  return VERSES.find(verse => verse.id === id);
};

export const getRandomVerseForTopic = (topicId: string): Verse | null => {
  const topicVerses = getVersesByTopic(topicId);
  if (topicVerses.length === 0) return null;
  return topicVerses[Math.floor(Math.random() * topicVerses.length)];
};

export const getRandomVerseForTopics = (topicIds: string[]): Verse | null => {
  const allVerses = VERSES.filter(verse => 
    verse.tags.some(tag => topicIds.includes(tag))
  );
  if (allVerses.length === 0) return null;
  return allVerses[Math.floor(Math.random() * allVerses.length)];
};
